baseurl = "https://yaragos.top/"
languageCode = "en-us"
paginate = 5
title = "Yaragos's Site"
copyright = "Yaragos"
defaultContentLanguage = "en"
hasCJKLanguage = true

# Show the last modification time of a page.
# To ensure the last modification time is correct,
# you need to set the timezone in .github/workflows/deploy.yml.
enableGitInfo = true

# theme = "hugo-theme-stack"
# Import the theme module.
[[module.imports]]
path = "github.com/CaiJimmy/hugo-theme-stack/v3"

# Permalinks format of each content section
[permalinks]
post = "/p/:slug/"
page = "/:slug/"

[params]
mainSections = ["post"]
featuredImageField = "image"
rssFullContent = true
favicon = "/img/favicon.png"

[params.footer]
since = 2024

[params.dateFormat]
published = "2006-01-02 15:04 MST"
lastUpdated = "2006-01-02 15:04 MST"

[params.sidebar]
emoji = "🍥"
subtitle = "Code never lies, comments sometimes do."

[params.sidebar.avatar]
enabled = true
local = true
src = "img/avatar.png"

[params.article]
math = true
toc = true
readingTime = true

[params.article.license]
enabled = true
default = "Licensed under CC BY-NC-SA 4.0"

# comments configuration
[params.comments]
enabled = true
provider = "utterances"

[params.comments.utterances]
repo = "yaragos/yaragos.github.io"
issueTerm = "pathname"
label = "Utterances"

[params.comments.giscus]
reactionsEnabled = 1
emitMetadata = 0

# widgets in left sidebar on homepage or page
[[params.widgets.homepage]]
type = "search"

[[params.widgets.homepage]]
type = "archives"

[params.widgets.homepage.params]
limit = 5

[[params.widgets.homepage]]
type = "categories"

[params.widgets.homepage.params]
limit = 15

[[params.widgets.homepage]]
type = "tag-cloud"

[params.widgets.homepage.params]
limit = 20

[[params.widgets.page]]
type = "toc"

[params.colorScheme]
toggle = true
default = "auto"

[params.imageProcessing.cover]
enabled = true

[params.imageProcessing.content]
enabled = true

# menu configuration
[[menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = -70
[menu.main.params]
icon = "tag"

[[menu.social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/yaragos/"
[menu.social.params]
icon = "brand-github"

[related]
includeNewer = true
threshold = 60
toLower = false

[[related.indices]]
name = "tags"
weight = 100

[[related.indices]]
name = "categories"
weight = 200

# Markdown renderer configuration (https://gohugo.io/content-management/markup/#goldmark)
[markup.goldmark.renderer]
unsafe = true
hardWraps = true

[markup.tableOfContents]
endLevel = 4
ordered = true
startLevel = 2

[markup.highlight]
noClasses = false
codeFences = true
guessSyntax = true
lineNoStart = 1
lineNos = true
lineNumbersInTable = true
tabWidth = 4

[frontmatter]
# lastmod = [":git", "lastmod", ":fileModTime"]
lastmod = ["lastmod", ":git", ":fileModTime", "date", "publishDate"]

