[algorithm]
aliases = ["algorithm"]
title = "算法"
description = "以基础算法为主"
image = "images/categories/algorithm.jpg"

[backend]
aliases = ["backend"]
title = "大后端"
description = "后端技术和框架，不限语言"
image = "images/categories/backend.webp"

[frontend]
aliases = ["frontend"]
title = "大前端"
description = "前端技术和框架，不限语言"
image = "images/categories/frontend.jpeg"

[golang]
aliases = ["golang", "go"]
title = "Golang"
description = "Golang 相关"
image = "images/categories/golang.png"

[java]
aliases = ["java"]
title = "Java"
description = "Java 相关"
image = "images/categories/java.png"

[linux]
aliases = ["linux"]
title = "Linux"
description = "Linux 相关学习笔记"
image = "images/categories/linux.png"

[mumbles]
aliases = ["mumbles", "碎碎念"]
title = "碎碎念"
description = "分享日常心情、随想杂谈和生活中的点滴"
image = "images/categories/mumbles.jpg"
